[package]
name = "mth"
version = "0.1.0"
authors = ["uncoder-fe"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.4.2" }
chrono = "0.4"
pulldown-cmark = "0.2.0"
handlebars = "1.1.0"
serde_json = "1.0"